### PR TITLE
feat(ListNP): fixed edge-case and error handling

### LINKED ISSUE #3173: fix(NPAPI): failed NPCreate resource creation causes NPList to return 500s
**Describe the bug**

When node pool creation fails at resource creation, such as specifying invalid volume size, the database entry of the invalid node pool is left intact.
In these cases if a node pool list is requested afterwards, it responds with a `500 Internal Server Errror` because the corresponding resource description call fails.

**Steps to reproduce the issue:**

1. create an EKS cluster.
2. Use the following node pool create template to initiate a node pool creation with invalid volume size
```yaml
# ~/banzai_cluster_nodepool_create.yaml
name: node-pool
size: 1
instanceType: t2.small
autoscaling:
  enabled: true
  minSize: 1
  maxSize: 2
spotPrice: "0.02"
volumeSize: 1
```
3. Wait for the node pool creation to fail.
4. Observe the node pool creation failure error to be `selected volume size of 1 GB (source: explicitly set) is less than the AMI size of 20 GB`.
5. Try listing the node pools with `banzai cluster node pool list`.
6. Observe the `500 Internal Server Error` response.
```shell
ERRO[0002] failed to list node pools: 500 Internal Server Error (err pipeline.GenericOpenAPIError, request=5, response={"type":"about:blank","title":"Internal Server Error","status":500,"detail":"something went wrong","code":500,"messa
ge":"something went wrong","error":"something went wrong"}
) 
2020/09/18 09:24:38 could not list node pools: 500 Internal Server Error
```
7. Check the corresponding Pipeline API logs to contain the related error message.
```shell
ERRO[3783] listing node pools through EKS service failed: listing node pools failed: retrieving node pool cloudformation stack failed: ValidationError: Stack with id pipeline-eks-nodepool-pregnor-3161-valid-volume-size-cluster-create-node-pool does not exist
        status code: 400, request id: 450d427f-2f83-470e-af46-c848ba7c1906  application=pipeline cluster="{5 e5ea99a0-5d36-4fb5-ad6b-8d2a326c82de pregnor-3161-valid-volume-size-cluster-create 1 WARNING selected volume size of 15 GB (source: explicitly set) is less than the AMI size of 20 GB amazon eks eu-central-1 brn:1:secret:44a1341833e8b5c57133c0112d92f62d4b052f48aab6a9297b3effe87d786e51 brn:1:secret:2713ee6d73d8aa8c05fea05ccc41e08ec56b311ff1cce476d614190a3acb6aa4 map[]}" clusterID=5 file="distribution_eks.go:78" func=eksService.ListNodePools input="{\n  StackName: \"pipeline-eks-nodepool-pregnor-3161-valid-volume-size-cluster-create-node-pool\"\n}" nodePoolNames="[pool1 pool2 node-pool]"
```

**Expected behavior**

Node pool listing should succeed for the existing database entries with the invalid/not created node pool's values indicating there is no corresponding node pool resource.

**Screenshots**

-

**Additional context**

As we would like to have database records for failed node pools as well, my suggestion would be to fix the node pool listing logic to handle not existing node pools gracefully.

I believe this is a generic issue with failed-to-create node pools which are already added to the database, but have no corresponding backing resource, it is not related in any way to the volume size, that's just an easy way of reproduction and the way I found it during manual tests.

### PR DESCRIPTION
**Pull request by pregnor**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | resolves #3173 
| License         | Apache 2.0

### What's in this PR?

Added status to `ListNodePools` output and fixed node pool creation edge cases.

### Why?

Because there were issues with node pool listing when the CF stack creation failed, was not started yet or the stack was already deleted.

### Additional context

CLI [PR](https://github.com/banzaicloud/banzai-cli/pull/312).
Documentation [PR](https://github.com/banzaicloud/banzaicloud.github.io/pull/1854).

One issue was partially due to using stack name for description which fails in case of deleted stacks.

Another issue was that if the node pool creation validation failed, no stacks exists at that point, but the database has the node pool already.

Another implicit issue was that when the node pool create validation succeeds, but the CF stack create hasn't started yet, the node pool listing could still fail due to not existing stack.

4 approaches were considered for DB stack ID update:
1. add DB update activity around `CreateASGActivity` and return the stack ID from `CreateASGActivity`.
2. split `CreateASGActivity`
3. change `CreateASGActivity` to workflow with multiple subactivities.
4. add DB changing to CreateASGActivity (chosen)

The `CreateASGActivity` executes further actions after retrieving the stack ID from `CreateStack` and can fail later and also the Cadence activity output synchronization according to its documentation either returns an output value or an error and not both which means I could not return the stack ID and potential further errors in those cases.
I think the activity executes a logical unit and should not be split because of that.
The third approach would only make sense if we were restricting actions such as database modification to workflows and disallow those in activities, haven't experienced such distinction yet, but correct me if I'm wrong.

#### Test matrix (tested with PR CLI variant for simplicity)

```yaml
creationStates:
    - operations:
        - cluster create
        - cluster update (with new node pools)
        - node pool create
    - stateChangesToCheck:
        - Not existing -> Creating -> Error (pre-stack, validation failed)
        - Not existing -> Creating -> Ready
deletionStates:
    - operations:
        - node pool delete
        - cluster delete
    - stateChangesToCheck:
        - Error -> Deleting -> Deleted
        - Ready -> Deleting -> Deleted
```

<details>

  <summary>Cluster create, Not existing -> Creating -> Error</summary>

```yaml
# ~/banzai_cluster_create.yaml
name: pregnor-3173-error
location: eu-central-1
cloud: amazon
secretName: aws-pregnor
properties:
  eks:
    version: "1.17.9"
    nodePools:
      pool1:
        spotPrice: "0.01"
        count: 1
        minCount: 1
        maxCount: 2
        autoscaling: true
        volumeSize: 20
        instanceType: t2.small
      node-pool:
        spotPrice: "0.01"
        count: 1
        minCount: 1
        maxCount: 2
        autoscaling: true
        volumeSize: 19
        instanceType: t2.small
```
```shell
banzai cluster create --file ~/banzai_cluster_create.yaml 

? Do you want a recommendation on your node groups? No
The current state of the request:

{
  "cloud": "amazon",
  "location": "eu-central-1",
  "name": "pregnor-3173-error",
  "properties": {
    "eks": {
      "nodePools": {
        "node-pool": {
          "autoscaling": true,
          "count": 1,
          "instanceType": "t2.small",
          "maxCount": 2,
          "minCount": 1,
          "spotPrice": "0.01",
          "volumeSize": 19
        },
        "pool1": {
          "autoscaling": true,
          "count": 1,
          "instanceType": "t2.small",
          "maxCount": 2,
          "minCount": 1,
          "spotPrice": "0.01",
          "volumeSize": 20
        }
      },
      "version": "1.17.9"
    }
  },
  "secretName": "aws-pregnor"
}
? Do you want to edit the cluster request in your text editor? No
? Do you want to CREATE the cluster "pregnor-3173-error" now? Yes
INFO[0014] cluster is being created                     
INFO[0014] you can check its status with the command `banzai cluster get "pregnor-3173-error"` 
Id  Name              
8   pregnor-3173-error

> while true ; do build/banzai cluster list ; build/banzai cluster --cluster-name pregnor-3173-error nodepool list ; sleep 1 ; done

Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status    StatusMessage                  
Error: could not find cluster named "pregnor-3173-error"
Usage:
  banzai cluster nodepool list [flags]

Aliases:
  list, l, ls

Flags:
      --cluster int32         ID of cluster to nodepool-list
      --cluster-name string   Name of cluster to nodepool-list
  -h, --help                  help for list

Global Flags:
      --color                use colors on non-tty outputs
      --config string        config file (default is $BANZAICONFIG or $HOME/.banzai/config.yaml)
      --interactive          ask questions interactively even if stdin or stdout is non-tty
      --no-color             never display color output
      --no-interactive       never ask questions interactively
      --organization int32   organization id
  -o, --output string        output format (default|yaml|json) (default "default")
      --verbose              more verbose output

could not find cluster named "pregnor-3173-error"
...
Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status    StatusMessage                  
8   pregnor-3173-error  eks           eu-central-1  1.17.9   pregnor      2020-09-28T15:56:53+02:00  CREATING  Cluster creation is in progress
ERRO[0000] failed to list node pools: 409 Conflict (err pipeline.GenericOpenAPIError, request=16, response={"type":"about:blank","title":"Conflict","status":409,"detail":"cluster is not ready","code":409,"message":"cluster is not ready","error":"cluster is not ready"}
) 
2020/09/30 15:43:58 could not list node pools: 409 Conflict
...
Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status   StatusMessage                                                                            
8   pregnor-3173-error  eks           eu-central-1  1.17.9   pregnor      2020-09-28T15:56:53+02:00  ERROR    selected volume size of 19 GB (source: explicitly set) is less than the AMI size of 20 GB
ERRO[0000] failed to list node pools: 409 Conflict (err pipeline.GenericOpenAPIError, request=16, response={"type":"about:blank","title":"Conflict","status":409,"detail":"cluster is not ready","code":409,"message":"cluster is not ready","error":"cluster is not ready"}
) 
2020/09/30 15:59:54 could not list node pools: 409 Conflict
```

</details>

<details>

  <summary>Cluster create, Not existing -> Creating -> Ready</summary>

```yaml
# ~/banzai_cluster_create.yaml
name: pregnor-3173-ready
location: eu-central-1
cloud: amazon
secretName: aws-pregnor
properties:
  eks:
    version: "1.17.9"
    nodePools:
      pool1:
        spotPrice: "0.01"
        count: 1
        minCount: 1
        maxCount: 2
        autoscaling: true
        volumeSize: 20
        instanceType: t2.small
      node-pool:
        spotPrice: "0.01"
        count: 1
        minCount: 1
        maxCount: 2
        autoscaling: true
        volumeSize: 21
        instanceType: t2.small
```

```shell
> banzai cluster create --file ~/banzai_cluster_create.yaml 

? Do you want a recommendation on your node groups? No
The current state of the request:

{
  "cloud": "amazon",
  "location": "eu-central-1",
  "name": "pregnor-3173-ready",
  "properties": {
    "eks": {
      "nodePools": {
        "node-pool": {
          "autoscaling": true,
          "count": 1,
          "instanceType": "t2.small",
          "maxCount": 2,
          "minCount": 1,
          "spotPrice": "0.01",
          "volumeSize": 21
        },
        "pool1": {
          "autoscaling": true,
          "count": 1,
          "instanceType": "t2.small",
          "maxCount": 2,
          "minCount": 1,
          "spotPrice": "0.01",
          "volumeSize": 20
        }
      },
      "version": "1.17.9"
    }
  },
  "secretName": "aws-pregnor"
}
? Do you want to edit the cluster request in your text editor? No
? Do you want to CREATE the cluster "pregnor-3173-ready" now? Yes
INFO[0011] cluster is being created                     
INFO[0011] you can check its status with the command `banzai cluster get "pregnor-3173-ready"` 
Id  Name              
9   pregnor-3173-ready

> while true ; do build/banzai cluster list ; build/banzai cluster --cluster-name pregnor-3173-ready nodepool list ; sleep 1 ; done

Id  Name          Distribution  Location      Version  CreatorName  CreatedAt                  Status   StatusMessage     
7   pregnor-3173  eks           eu-central-1  1.17.9   pregnor      2020-09-19T09:18:40+02:00  RUNNING  Cluster is running
Error: could not find cluster named "pregnor-3173-ready"
Usage:
  banzai cluster nodepool list [flags]

Aliases:
  list, l, ls

Flags:
      --cluster int32         ID of cluster to nodepool-list
      --cluster-name string   Name of cluster to nodepool-list
  -h, --help                  help for list

Global Flags:
      --color                use colors on non-tty outputs
      --config string        config file (default is $BANZAICONFIG or $HOME/.banzai/config.yaml)
      --interactive          ask questions interactively even if stdin or stdout is non-tty
      --no-color             never display color output
      --no-interactive       never ask questions interactively
      --organization int32   organization id
  -o, --output string        output format (default|yaml|json) (default "default")
      --verbose              more verbose output

could not find cluster named "pregnor-3173-ready"
...
Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status    StatusMessage                  
9   pregnor-3173-ready  eks           eu-central-1  1.17.9   pregnor      2020-09-28T16:24:52+02:00  CREATING  Cluster creation is in progress
ERRO[0000] failed to list node pools: 409 Conflict (err pipeline.GenericOpenAPIError, request=17, response={"type":"about:blank","title":"Conflict","status":409,"detail":"cluster is not ready","code":409,"message":"cluster is not ready","error":"cluster is not ready"}
) 
2020/09/30 16:00:51 could not list node pools: 409 Conflict
...
Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status    StatusMessage                  
9   pregnor-3173-ready  eks           eu-central-1  1.17.9   pregnor      2020-09-28T16:24:52+02:00  CREATING  Cluster creation is in progress
Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
node-pool  1     Enabled      1            2            21          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d1c35b3e7cdcbe4b  READY                
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d1c35b3e7cdcbe4b  READY                
...
Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status    StatusMessage                  
9   pregnor-3173-ready  eks           eu-central-1  1.17.9   pregnor      2020-09-28T16:24:52+02:00  RUNNING  Cluster creation is in progress
Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
node-pool  1     Enabled      1            2            21          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d1c35b3e7cdcbe4b  READY                
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d1c35b3e7cdcbe4b  READY     
```

</details>

<details>

  <summary>Cluster update, Not existing -> Creating -> Error</summary>

```shell
> curl --location --request PUT 'https://localhost:9090/pipeline/api/v1/orgs/1/clusters/7' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ${TOKEN}' \
--data-raw '{
	"cloud": "amazon",
	"properties": {
		"eks": {
			"nodePools": {
				"pool1": {
                    "spotPrice": "0.01", 
                    "count": 1,
	                "minCount": 1,
	                "maxCount": 2,
            		"autoscaling": true,
                    "volumeSize": 20,
                    "instanceType": "t2.small"
            	},
            	"node-pool": {
	            	"spotPrice": "0.02",
                    "count": 1,
	                "minCount": 1,
	                "maxCount": 2,
            		"autoscaling": true, 
                    "volumeSize": 19,
            		"instanceType": "t2.small"
            	}
			}
		}
	}
}'

> while true ; do build/banzai cluster --cluster-name pregnor-3173 nodepool list ; sleep 1 ; done

Name   Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
pool1  1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                
...
Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status    StatusMessage
node-pool  0     Disabled     0            0            0                                                                                     CREATING               
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                  
...
Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage                                                                                                                             
node-pool  0     Disabled     0            0            0                                                                                     ERROR   Validation failed: selecting volume size failed: selected volume size of 19 GB (source: explicitly set) is less than the AMI size of 20 GB
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                                                                                                                          
```

</details>

<details>

  <summary>Cluster update, Not existing -> Creating -> Ready</summary>

```shell
> curl --location --request PUT 'https://localhost:9090/pipeline/api/v1/orgs/1/clusters/7' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ${TOKEN}' \
--data-raw '{
	"cloud": "amazon",
	"properties": {
		"eks": {
			"nodePools": {
				"pool1": {
                    "spotPrice": "0.01", 
                    "count": 1,
	                "minCount": 1,
	                "maxCount": 2,
            		"autoscaling": true,
                    "volumeSize": 20,
                    "instanceType": "t2.small"
            	},
            	"node-pool": {
	            	"spotPrice": "0.02",
                    "count": 1,
	                "minCount": 1,
	                "maxCount": 2,
            		"autoscaling": true, 
                    "volumeSize": 21,
            		"instanceType": "t2.small"
            	}
			}
		}
	}
}'

> while true ; do build/banzai cluster --cluster-name pregnor-3173 nodepool list ; sleep 1 ; done

Name   Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
pool1  1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                
...
Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status    StatusMessage
node-pool  1     Enabled      1            2            21          t2.small      ami-065ebfccbbb1c5734  0.02       subnet-0d922e468626e9e3f  CREATING               
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                  
...
Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
node-pool  1     Enabled      1            2            21          t2.small      ami-065ebfccbbb1c5734  0.02       subnet-0d922e468626e9e3f  READY                
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                
```

</details>

<details>

  <summary>Node pool create, Not existing -> Creating -> Error</summary>

```yaml
# ~/banzai_cluster_nodepool_create.yaml
name: node-pool
size: 1
instanceType: t2.small
autoscaling:
  enabled: true
  minSize: 1
  maxSize: 2
spotPrice: "0.02"
volumeSize: 19
image: ami-065ebfccbbb1c5734
```

```shell
> banzai cluster --cluster-name pregnor-3173 nodepool create --file ~/banzai_cluster_nodepool_create.yaml 

> while true ; do build/banzai cluster --cluster-name pregnor-3173 nodepool list ; sleep 1 ; done
Name   Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
pool1  1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                
...
Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage                                                                                                                             
node-pool  0     Disabled     0            0            0                                                                                     ERROR   Validation failed: selecting volume size failed: selected volume size of 19 GB (source: explicitly set) is less than the AMI size of 20 GB
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                                                                                                                          
```

</details>

<details>

  <summary>Node pool create, Not existing -> Creating -> Ready</summary>

```yaml
# ~/banzai_cluster_nodepool_create.yaml
name: node-pool
size: 1
instanceType: t2.small
autoscaling:
  enabled: true
  minSize: 1
  maxSize: 2
spotPrice: "0.02"
volumeSize: 21
image: ami-065ebfccbbb1c5734
```

```shell
> banzai cluster --cluster-name pregnor-3173 nodepool create --file ~/banzai_cluster_nodepool_create.yaml 

> while true ; do build/banzai cluster --cluster-name pregnor-3173 nodepool list ; sleep 1 ; done
Name   Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
pool1  1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                
...
Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status    StatusMessage
node-pool  1     Enabled      1            2            21          t2.small      ami-065ebfccbbb1c5734  0.02       subnet-0d922e468626e9e3f  CREATING               
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                  
...
Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
node-pool  1     Enabled      1            2            21          t2.small      ami-065ebfccbbb1c5734  0.02       subnet-0d922e468626e9e3f  READY                
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                
```

</details>

<details>

  <summary>Cluster delete, Error -> Deleting -> Deleted</summary>

```shell
> banzai cluster delete --cluster-name pregnor-3173-error

Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status  StatusMessage                                                                            
8   pregnor-3173-error  eks           eu-central-1  1.17.9   pregnor      2020-09-28T15:56:53+02:00  ERROR   selected volume size of 19 GB (source: explicitly set) is less than the AMI size of 20 GB
? Do you want to DELETE the cluster? Yes
INFO[0002] Deleting cluster &{202 Accepted 202 HTTP/1.1 1 1 map[Content-Length:[0] Date:[Mon, 28 Sep 2020 14:16:53 GMT]] 0xc00000c100 0 [] false false map[] 0xc0003d4f00 0xc000271970} 
Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status    StatusMessage             
8   pregnor-3173-error  eks           eu-central-1  1.17.9   pregnor      2020-09-28T15:56:53+02:00  DELETING  Termination is in progress

> while true ; do build/banzai cluster list ; build/banzai cluster --cluster-name pregnor-3173-error nodepool list ; sleep 1 ; done

Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status   StatusMessage                                                                            
8   pregnor-3173-error  eks           eu-central-1  1.17.9   pregnor      2020-09-28T15:56:53+02:00  ERROR    selected volume size of 19 GB (source: explicitly set) is less than the AMI size of 20 GB
ERRO[0000] failed to list node pools: 409 Conflict (err pipeline.GenericOpenAPIError, request=17, response={"type":"about:blank","title":"Conflict","status":409,"detail":"cluster is not ready","code":409,"message":"cluster is not ready","error":"cluster is not ready"}
) 
2020/09/30 16:00:51 could not list node pools: 409 Conflict
...
Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status    StatusMessage             
8   pregnor-3173-error  eks           eu-central-1  1.17.9   pregnor      2020-09-28T15:56:53+02:00  DELETING  Termination is in progress
ERRO[0000] failed to list node pools: 409 Conflict (err pipeline.GenericOpenAPIError, request=17, response={"type":"about:blank","title":"Conflict","status":409,"detail":"cluster is not ready","code":409,"message":"cluster is not ready","error":"cluster is not ready"}
) 
2020/09/30 16:00:51 could not list node pools: 409 Conflict
...
Id  Name          Distribution  Location      Version  CreatorName  CreatedAt                  Status   StatusMessage     
Error: could not find cluster named "pregnor-3173-error"
Usage:
  banzai cluster nodepool list [flags]

Aliases:
  list, l, ls

Flags:
      --cluster int32         ID of cluster to nodepool-list
      --cluster-name string   Name of cluster to nodepool-list
  -h, --help                  help for list

Global Flags:
      --color                use colors on non-tty outputs
      --config string        config file (default is $BANZAICONFIG or $HOME/.banzai/config.yaml)
      --interactive          ask questions interactively even if stdin or stdout is non-tty
      --no-color             never display color output
      --no-interactive       never ask questions interactively
      --organization int32   organization id
  -o, --output string        output format (default|yaml|json) (default "default")
      --verbose              more verbose output

could not find cluster named "pregnor-3173-error"
```

</details>

<details>

  <summary>Cluster delete, Ready -> Deleting -> Deleted</summary>

```shell
> banzai cluster delete --cluster-name pregnor-3173-ready

Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status   StatusMessage     
9   pregnor-3173-ready  eks           eu-central-1  1.17.9   pregnor      2020-09-28T16:24:52+02:00  RUNNING  Cluster is running
? Do you want to DELETE the cluster? Yes
INFO[0003] Deleting cluster &{202 Accepted 202 HTTP/1.1 1 1 map[Content-Length:[0] Date:[Mon, 28 Sep 2020 14:46:54 GMT]] 0xc00046c3e0 0 [] false false map[] 0xc0000da300 0xc0003c0fd0} 
Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status    StatusMessage             
9   pregnor-3173-ready  eks           eu-central-1  1.17.9   pregnor      2020-09-28T16:24:52+02:00  DELETING  Termination is in progress

> while true ; do build/banzai cluster list ; build/banzai cluster --cluster-name pregnor-3173-ready nodepool list ; sleep 1 ; done

Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status   StatusMessage     
9   pregnor-3173-ready  eks           eu-central-1  1.17.9   pregnor      2020-09-28T16:24:52+02:00  RUNNING  Cluster is running
Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
node-pool  1     Enabled      1            2            21          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-08a90988ab5f12a36  READY                
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-08a90988ab5f12a36  READY                
...
Id  Name                Distribution  Location      Version  CreatorName  CreatedAt                  Status    StatusMessage             
9   pregnor-3173-ready  eks           eu-central-1  1.17.9   pregnor      2020-09-28T16:24:52+02:00  DELETING  Termination is in progress
ERRO[0000] failed to list node pools: 409 Conflict (err pipeline.GenericOpenAPIError, request=17, response={"type":"about:blank","title":"Conflict","status":409,"detail":"cluster is not ready","code":409,"message":"cluster is not ready","error":"cluster is not ready"}
) 
2020/09/30 16:22:15 could not list node pools: 409 Conflict
...
Id  Name          Distribution  Location      Version  CreatorName  CreatedAt                  Status   StatusMessage     
Error: could not find cluster named "pregnor-3173-ready"
Usage:
  banzai cluster nodepool list [flags]

Aliases:
  list, l, ls

Flags:
      --cluster int32         ID of cluster to nodepool-list
      --cluster-name string   Name of cluster to nodepool-list
  -h, --help                  help for list

Global Flags:
      --color                use colors on non-tty outputs
      --config string        config file (default is $BANZAICONFIG or $HOME/.banzai/config.yaml)
      --interactive          ask questions interactively even if stdin or stdout is non-tty
      --no-color             never display color output
      --no-interactive       never ask questions interactively
      --organization int32   organization id
  -o, --output string        output format (default|yaml|json) (default "default")
      --verbose              more verbose output

could not find cluster named "pregnor-3173-ready"
```

</details>

<details>

  <summary>Node pool delete, Error -> Deleting -> Deleted</summary>

```shell
> banzai cluster --cluster-name pregnor-3173 nodepool delete node-pool

delete process initiated for node pool 'node-pool'

> while true ; do build/banzai cluster --cluster-name pregnor-3173 nodepool list ; sleep 1 ; done

Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
node-pool  1     Enabled      1            2            19          t2.small      ami-065ebfccbbb1c5734  0.02       subnet-0d922e468626e9e3f  ERROR   Validation failed: selecting volume size failed: selected volume size of 19 GB (source: explicitly set) is less than the AMI size of 20 GB                
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                
...
Name   Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
pool1  1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                
```

</details>

<details>

  <summary>Node pool delete, Ready -> Deleting -> Deleted</summary>

```shell
> banzai cluster --cluster-name pregnor-3173 nodepool delete node-pool

delete process initiated for node pool 'node-pool'

> while true ; do build/banzai cluster --cluster-name pregnor-3173 nodepool list ; sleep 1 ; done

Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
node-pool  1     Enabled      1            2            21          t2.small      ami-065ebfccbbb1c5734  0.02       subnet-0d922e468626e9e3f  READY                
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                
...
Name       Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status    StatusMessage
node-pool  1     Enabled      1            2            21          t2.small      ami-065ebfccbbb1c5734  0.02       subnet-0d922e468626e9e3f  DELETING               
pool1      1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                  
...
Name   Size  Autoscaling  MinimumSize  MaximumSize  VolumeSize  InstanceType  Image                  SpotPrice  SubnetID                  Status  StatusMessage
pool1  1     Enabled      1            2            20          t2.small      ami-065ebfccbbb1c5734  0.01       subnet-0d922e468626e9e3f  READY                
```

</details>

### Checklist

- [x] Implementation tested (with at least one cloud provider)
- [X] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] OpenAPI and Postman files updated (if needed)
- [x] User guide and development docs updated (if needed)
- ~Related Helm chart(s) updated (if needed)~

### CODE REVIEW

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go [hunk 1]
```diff
@@ -125,42 +126,68 @@ func generateNodePoolStackName(clusterName string, poolName string) string {
...
+				// in a healthy state, thus CF stack creation has not been
+				// started yet due to the operation order.
+				nodePool.Status = eks.NodePoolStatusCreating
+				nodePool.StatusMessage = ""
+			} else if isCreating && hasError {
+				// Note: node pool creation failed before the CF stack creation
+				// would have been started thus no CF stack is available to
+				// describe.
+				nodePool.Status = eks.NodePoolStatusError
+				nodePool.StatusMessage = fmt.Sprintf("Creating node pool failed: %s", c.StatusMessage)
```
Comment (pregnor) [inline internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:185]: **Note**: this is not correct in case the user issues an operation unrelated to the failed to create node pool and then lists the node pools.

So 
1. create invalid node pool
2. node pool create validation fails
3. list node pools (returns correct failure message)
4. create valid node pool || create differently invalid node pool || delete cluster || ...
5. list node pools (returns incorrect failure message as the last cluster status message is not the node pool failure message)

I'm going to think about how this could be done without stored node pool status messages, because I wanted to avoid that deliberately (probably that's the subconscious reason why I haven't caught this earlier).

I don't see any other solution right now and that (storing status message) feels a little bit overkill for the edge case of the edge case (I mean why would anyone leave a failed to create node pool as is), but for completeness this needs to be fixed.

Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:185]: Yeah, the whole cluster status fallback is very fragile and not reliable due to possible other unrelated operations run after the describe failure node pool is introduced.

Right now I don't think we can avoid storing the node pool status and status message in the database as a fallback for cases when the describing the stack fails.

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go [hunk 2]
```diff
@@ -147,21 +149,29 @@ func (n nodePoolManager) ListNodePools(ctx context.Context, cluster cluster.Clus
...
+
 		stackName := generateNodePoolStackName(cluster.Name, nodePoolName)
 		describeStacksInput.StackName = &stackName
 		stackDescriptions, err := cfClient.DescribeStacks(&describeStacksInput)
 		if err != nil {
-			return nil, errors.WrapWithDetails(err, "retrieving node pool cloudformation stack failed",
-				"cluster", cluster,
-				"input", describeStacksInput,
-			)
+			nodePool.Status = eks.NodePoolStatusError
```
[the remark this answers is not in the document]
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go]: It could be that as well.

This code is later modified to be more sophisticated, but your comment is still relevant in that context so I'm going to consider using unknown here instead of error, not decided yet.

[the remark this answers is not in the document]
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go]: Yeah, I think unknown would fit better here.

[the remark this answers is not in the document]
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go]: It could be that as well.

This code is later modified to be more sophisticated, but your comment is still relevant in that context so I'm going to consider using unknown here instead of error.

Yeah, I think unknown would fit better here.

[the remark this answers is not in the document]
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go]: [Fixed](https://github.com/banzaicloud/pipeline/compare/f513dae37072b38a31753d8ddb5a981e4c878eb9..c5c7b1f092402fc85cfe94368f1384ec9f5f5bb1).

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go (hunk 1 above)
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go]: [Fixed](https://github.com/banzaicloud/pipeline/compare/82c01a8999f6b30ef6da3428b2d2043d054ed781..f150e2ca28b67797e2d68b99c2593373ef1bbfc8).

**Comment by pregnor** [comment]
Retested using the matrix with the latest state, everything passed as expected.

File: internal/cluster/distribution/eks/service.go [hunk 3]
```diff
@@ -85,15 +84,76 @@ type NodePoolUpdateDrainOptions struct {
...
+	// resources are being changed.
+	NodePoolStatusUpdating NodePoolStatus = "UPDATING"
+)
+
+// NewNodePoolStatusFromCFStackStatus translates a CloudFormation stack status
+// into a node pool status.
+func NewNodePoolStatusFromCFStackStatus(cfStackStatus string) (nodePoolStatus NodePoolStatus) {
+	switch {
+	case strings.HasSuffix(cfStackStatus, "_COMPLETE"):
+		if cfStackStatus == "DELETE_COMPLETE" { // Note: CF stack is deleted, but DB entry is still existing.
```
Comment (bonifaido) [inline internal/cluster/distribution/eks/service.go:139]: There are some nice constants for these values like: `ChangeSetStatusDeleteComplete` in the `cloudformation` package of the AWS SDK. I guess because the substring matching they are not used, just a notic.

Comment (pregnor) [reply internal/cluster/distribution/eks/service.go:139]: That's correct, also I was unsure of whether we want to references those from here, but I'm going to replace the exact values with those constants.

**Review by bonifaido — APPROVED** [review]

File: internal/cluster/distribution/eks/service.go (hunk 3 above)
Comment (pregnor) [reply internal/cluster/distribution/eks/service.go]: [Fixed](https://github.com/banzaicloud/pipeline/compare/e5f64f3bea2496abc75b55cb13b0cee1651d9793..f92f6f4a1158cc11e4b9a495b58a3bf3cb952702).

File: internal/cluster/distribution/eks/eksprovider/workflow/create_infra.go [hunk 4]
```diff
@@ -70,9 +73,19 @@ type CreateInfrastructureWorkflowOutput struct {
...
+	nodePoolStore eks.NodePoolStore
+}
+
+func NewCreateInfrastructureWorkflow(nodePoolStore eks.NodePoolStore) (createInfrastructureWorkflow *CreateInfrastructureWorkflow) {
+	return &CreateInfrastructureWorkflow{
+		nodePoolStore: nodePoolStore,
+	}
+}
+
 // CreateInfrastructureWorkflow executes the Cadence workflow responsible for creating EKS
```
Comment (orymate) [inline internal/cluster/distribution/eks/eksprovider/workflow/create_infra.go:86]:
```suggestion
// Execute executes the Cadence workflow responsible for creating EKS
```

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go [hunk 5]
```diff
@@ -123,45 +126,91 @@ func generateNodePoolStackName(clusterName string, poolName string) string {
...
 		if err != nil {
-			return nil, errors.WrapWithDetails(err, "retrieving node pool cloudformation stack failed",
-				"cluster", cluster,
-				"input", describeStacksInput,
-			)
+			if existingNodePool.StackID == "" {
+				// Note: node pool is in the database already, but the stack is
+				// not existing thus it is either being created or failed
+				// creation with error before CloudFormation stack creation
+				// would have been started.
```
Comment (orymate) [inline internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:195]: This branch runs if the node pool is older than this db change

**Review by orymate — APPROVED** [review]

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go [hunk 6]
```diff
@@ -123,45 +126,91 @@ func generateNodePoolStackName(clusterName string, poolName string) string {
...
+			ID:             c.ID,
+			Name:           c.Name,
+		}
+	}
+
+	clusterClient, err := n.dynamicClientFactory.FromSecret(ctx, c.ConfigSecretID.String())
 	if err != nil {
-		return nil, errors.WrapWithDetails(err, "creating dynamic Kubernetes client factory failed", "cluster", cluster)
+		return nil, errors.WrapWithDetails(err, "creating dynamic Kubernetes client factory failed",
+			"OrganizationID", c.OrganizationID,
```
Comment (sagikazarmark) [inline internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:146]: Camel case is preferred at the moment and is/should be used: `organizationId`. Different casing can make searching the logs harder.

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go [hunk 7]
```diff
@@ -123,45 +126,91 @@ func generateNodePoolStackName(clusterName string, poolName string) string {
...
-	for _, nodePoolName := range nodePoolNames {
-		stackName := generateNodePoolStackName(cluster.Name, nodePoolName)
-		describeStacksInput.StackName = &stackName
+	nodePools = make([]eks.NodePool, 0, len(nodePools))
+	for _, existingNodePool := range existingNodePools {
+		nodePools = append(nodePools, eks.NodePool{
+			Name:   existingNodePool.Name,
+			Labels: labelSets[existingNodePool.Name],
+		})
+		nodePool := &nodePools[len(nodePools)-1]
```
Comment (sagikazarmark) [inline internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:181]: If the appending is moved to the end of the loop, we can avoid looking the nodepool up from the slice. Then it also doesn't have to be a pointer.

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go [hunk 8]
```diff
@@ -123,45 +126,91 @@ func generateNodePoolStackName(clusterName string, poolName string) string {
...
+
+		stackIdentifier := existingNodePool.StackID
+		if stackIdentifier == "" { // Note: CloudFormation stack creation not started yet.
+			stackIdentifier = generateNodePoolStackName(c.Name, existingNodePool.Name)
```
Comment (sagikazarmark) [inline internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:185]: Ideally, we should drop stack name generation at some point which means we won't be able to look it up by name either.

What's our plan for that case?

I could imagine sending a query to the running workflow, but then we need to address it somehow.

Or did I misunderstood something here? The comment indicates that this is a fallback for a non-existing stack, not an old node pool without a stack ID.

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go (hunk 7 above)
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:181]: If we move it there, we need to append at every early continue in "error handling" branches.

Is that preferred over this approach?

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go (hunk 8 above)
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:185]: Your understanding is correct, I haven't thought about stack name elimination yet, thinking about it now.

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go (hunk 5 above)
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:203]: [Fixed](https://github.com/banzaicloud/pipeline/compare/f92f6f4a1158cc11e4b9a495b58a3bf3cb952702..c5954624b93bec483e9730a46e4fd9672e3a365d).

File: internal/cluster/distribution/eks/eksprovider/workflow/create_infra.go (hunk 4 above)
Comment (pregnor) [reply internal/cluster/distribution/eks/eksprovider/workflow/create_infra.go]: [Fixed](https://github.com/banzaicloud/pipeline/compare/c5954624b93bec483e9730a46e4fd9672e3a365d..a66ed0a2166a67445eaa5df4ba76f2191ecc379f).

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go (hunk 6 above)
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:146]: I agree with a camelCase, this was a copy-paste typo (copied the field name).

I saw a very mixed bag of initialism though.
(The representation is non-exhaustive, the relative ratio felt around 40-60%.)

Upper case initialism organization ID (and cluster ID):
https://github.com/banzaicloud/pipeline/blob/master/internal/cluster/clusteradapter/gorm_clusters.go#L109
https://github.com/banzaicloud/pipeline/blob/master/internal/cluster/distribution/eks/eksprovider/driver/cluster_creator.go#L541
https://github.com/banzaicloud/pipeline/blob/master/internal/cluster/distribution/eks/eksprovider/driver/cluster_deleter.go#L96
https://github.com/banzaicloud/pipeline/blob/master/internal/cluster/distribution/eks/eksprovider/driver/cluster_updater.go#L342
https://github.com/banzaicloud/pipeline/blob/master/internal/helm/envresolver.go#L98

Mixed case initialism:
https://github.com/banzaicloud/pipeline/blob/master/internal/common/commonadapter/secret.go#L88
https://github.com/banzaicloud/pipeline/blob/master/internal/helm/charter.go#L153
https://github.com/banzaicloud/pipeline/blob/master/internal/helm/errors.go#L70

I'm going to update the initials in the changed code to mixed as you suggested, just wanted to let you know it's already very diverse.

Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go]: [Fixed](https://github.com/banzaicloud/pipeline/compare/a66ed0a2166a67445eaa5df4ba76f2191ecc379f..8bcf793d712a07b312bfd8dda9bf7b763367679a).

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go (hunk 8 above)
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:185]: If we have neither stack name nor stack ID yet, then we haven't started creating the stack yet (`CreateStack()` immediately returns a stack ID which is then saved to DB).

In such a case the node pool is either creating or failed with a pre-stack issue (such as validation).
For these we should rely on the DB stored status and status message (those are updated at node pool creation start and pre-stack validation failure) and fill the returned node pool with those values, just like it is done in the `err != nil` handling of the `DescribeStacks()` call in the current implementation.

We could also fill the DB stored creation parameter values of the node pool if we wish, but unless we have an incentive to do so I would avoid that as currently we are only storing node pool creation parameter values for legacy reasons and thus those are up for elimination.
I think a zero valued node pool with a correct `CREATING / ERROR` node pool status is sufficient, we don't actually need to fill the creation parameter values as the node pool is not created yet.

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go (hunk 7 above)
Comment (sagikazarmark) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:181]: Hm....

Maybe extract the body of the loop into a separate function and just return with a node pool?

That sounds better anyway than using a lot of continues.

Also, you could even extract some of the logic into smaller functions and return a node pool directly (functional approach).

For example this part:

> err = sdkCloudFormation.ParseStackParameters(stack.Parameters, &nodePoolParameters)

could go into a separate function, in the err case set the status and message and return a node pool, otherwise fill in the values in the node pool struct and return it.

It's up to you, not sure it's worth blocking the PR or rewriting the code, they are functionally the same, but it feels less readable now.

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go (hunk 8 above)
Comment (sagikazarmark) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:185]: We don't necessarily have to store it in the DB. We can send a query to the running cadence workflow, to return some information. It could return the original node pool create request. This sounds like the simplest solution to me at the moment, but we still have to solve:

> then we need to address it somehow

We need to know the process ID (workflow ID) for the create workflow, which we should know (somehow). But keep in mind: we need to do that for cluster creation and node pool creation as well. (Probably need to move node pool creation to child workflows and address them directly with queries)

If this is only an issue in a transient state, I'd say postpone it to a later PR.

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go (hunk 7 above)
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:181]: I agree, I like this approach, so I'm gonna implement it.

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go (hunk 8 above)
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:185]: Yes, it is only an issue in transient state (pre-stack creating and deleting states, but the latter is covered with the stack ID usage).
From the moment of starting stack creation we are going to be able to use the stack ID safely all the time.
So I agree with postponing the decision.

I'm getting used to the idea of accessing the async workflows directly (not against it, just gotta think about its trade-offs more before I can say I'm fine with it).
I guess it's up for debate which is better, to avoid storing such values or to avoid accessing running workflow information directly (with the latter being useful in a lot of other cases as well I feel).
In general I would also prefer derived dynamic state (running workflow details) over stored static state, so I can be easily convinced, just getting used to the idea.

Comment (sagikazarmark) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:185]: Let's open an issue with the details/links to this discussion then.

Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go:185]: https://github.com/banzaicloud/pipeline/issues/3195

File: internal/cluster/distribution/eks/eksadapter/node_pool_manager.go (hunk 7 above)
Comment (pregnor) [reply internal/cluster/distribution/eks/eksadapter/node_pool_manager.go]: [Fixed](https://github.com/banzaicloud/pipeline/pull/3187/commits/548febed09b25fe668a14074e8df06f0040031e9).

**Review by sagikazarmark — APPROVED** [review]
