### PR TITLE
Introduce new retry library and fix AKS etcd server unavailable error

### LINKED ISSUE #1611: AKS: retry all operations that fail with "etcdserver: request timed out"
The etcd server on AKS clusters is unstable (especially  after AKS cluster launch) thus various kubernetes operations (e.g. creating namespaces, pods etc) may fail with  "etcdserver: request timed out".

All kubernetes operations executed on AKS clusters must be retried in case it failed due to " "etcdserver: request timed out"

### PR DESCRIPTION
**Pull request by baluchicken**
Fixes #1611
Introduced a new retry library discussed in #1351

### CODE REVIEW

File: internal/backoff/backoff.go [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+	"github.com/lestrrat-go/backoff"
+)
+
+// NewConstantBackoffPolicy creates a new constant backoff policy
+func NewConstantBackoffPolicy(config *ConstantBackoffConfig) *backoff.Constant {
+	return backoff.NewConstant(config.Delay, backoff.WithMaxRetries(config.MaxRetries), backoff.WithMaxElapsedTime(config.MaxElapsedTime))
+}
+
+// RetryConstant retries the given function using constant backoff policy
+func RetryConstant(function func() error, backoffPolicy *backoff.Constant) (err error) {
```
Comment (orymate) [inline internal/backoff/backoff.go]: use iface

File: pkg/k8sutil/namespace.go [hunk 2]
```diff
@@ -44,3 +48,22 @@ func EnsureNamespaceWithLabel(client kubernetes.Interface, namespace string, lab
...
+
+// EnsureNamespaceWithLabelWithRetry creates a namespace with optional labels and retries if fails because of etcd timeout
+func EnsureNamespaceWithLabelWithRetry(client kubernetes.Interface, namespace string, labels map[string]string) (err error) {
+	var backoffConfig = backoff.ConstantBackoffConfig{
+		Delay:      time.Duration(10) * time.Second,
+		MaxRetries: 5,
+	}
+	var backoffPolicy = backoff.NewConstantBackoffPolicy(&backoffConfig)
+	err = backoff.RetryConstant(func() error {
+		err = EnsureNamespaceWithLabel(client, namespace, labels)
```
Comment (orymate) [inline pkg/k8sutil/namespace.go]:
```suggestion
		err: = EnsureNamespaceWithLabel(client, namespace, labels)
```

?

File: pkg/k8sutil/namespace.go [hunk 3]
```diff
@@ -44,3 +47,21 @@ func EnsureNamespaceWithLabel(client kubernetes.Interface, namespace string, lab
 
 	return nil
 }
+
+// EnsureNamespaceWithLabelWithRetry creates a namespace with optional labels and retries if fails because of etcd timeout
+func EnsureNamespaceWithLabelWithRetry(client kubernetes.Interface, namespace string, labels map[string]string) (err error) {
+	var backoffConfig = backoff.ConstantBackoffConfig{
+		Delay:      time.Duration(10) * time.Second,
```
Comment (orymate) [inline pkg/k8sutil/namespace.go]:
```suggestion
		Delay:      10 * time.Second,
```
