### PR TITLE
Fix non-deterministic map iterations in Cadence workflows

### LINKED ISSUE #2155: Non deterministic code in the UpdateClusterWorklfow
**Describe the bug**
Cadence workflow code must be deterministic to support workflow state recovery through event sourcing. This rules out use of range over map as Go runtime on purpose [randomizes iteration order](https://nathanleclaire.com/blog/2014/04/27/a-surprising-feature-of-golang-that-colored-me-impressed/).

**Steps to reproduce the issue:**
Execute workflow with [sticky execution off](https://github.com/uber-go/cadence-client/blob/103fa1e95de1a892571ccdef71ebca786e4728cb/internal/worker.go#L170).

**Expected behavior**
The code of all workflows (I've looked at UpdateClusterWorklfow only)  should be rewritten to not use range over map.

**Additional context**
Read [Implementation](https://cadenceworkflow.io/docs/03_goclient/02_create_workflows#implementation) section of the Cadence Go Documentation for more potential determinism gotchas.

### PR DESCRIPTION
**Pull request by sagikazarmark**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #2155
| License         | Apache 2.0

### What's in this PR?
Future map structures are converted to slices to ensure iterations are deterministic.

### Additional context

In some cases the implementation itself was affected. Please take that into account when reviewing.

### Checklist

~~- [-] Implementation tested (with at least one cloud provider)~~
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [x] Logging code meets the guideline (TODO)
- [x] OpenAPI and Postman files updated, client regenerated (`make generate-client`) (if needed)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

File: internal/providers/pke/pkeworkflow/update_cluster.go [hunk 1]
```diff
@@ -83,92 +83,128 @@ func UpdateClusterWorkflow(ctx workflow.Context, input UpdateClusterWorkflowInpu
...
 		}
 
-		futures[np.Name] = workflow.ExecuteActivity(ctx, DeletePoolActivityName, DeletePoolActivityInput{
-			// AWSActivityInput: awsActivityInput,
-			ClusterID: input.ClusterID,
-			Pool:      np,
-		})
-	}
+		errs := make([]error, len(futures))
+		for i, future := range futures {
```
Comment (orymate) [inline internal/providers/pke/pkeworkflow/update_cluster.go]:
```suggestion
		for i, future := range futures {
		if future != nil {
```

File: internal/providers/pke/pkeworkflow/update_cluster.go [hunk 2]
```diff
@@ -83,92 +83,128 @@ func UpdateClusterWorkflow(ctx workflow.Context, input UpdateClusterWorkflowInpu
...
+			errs[i] = errors.Wrapf(future.Get(ctx, nil), "couldn't delete node pool %q", input.NodePoolsToDelete[i].Name)
```
Comment (orymate) [inline internal/providers/pke/pkeworkflow/update_cluster.go]:
```suggestion
				errs[i] = errors.Wrapf(future.Get(ctx, nil), "couldn't delete node pool %q", input.NodePoolsToDelete[i].Name)
			}
```

File: internal/providers/pke/pkeworkflow/update_cluster.go [hunk 3]
```diff
@@ -83,92 +83,128 @@ func UpdateClusterWorkflow(ctx workflow.Context, input UpdateClusterWorkflowInpu
...
+				ExternalBaseUrlInsecure:   input.PipelineExternalURLInsecure,
+				SSHKeyName:                "pke-ssh-" + input.ClusterName,
+			}
+
+			futures[i] = workflow.ExecuteActivity(ctx, CreateWorkerPoolActivityName, createWorkerPoolActivityInput)
+		}
+
+		errs := make([]error, len(futures))
+		for i, future := range futures {
+			errs[i] = errors.Wrapf(future.Get(ctx, nil), "couldn't create node pool %q", input.NodePoolsToAdd[i].Name)
```
Comment (orymate) [inline internal/providers/pke/pkeworkflow/update_cluster.go]: to be honest, I don't feel this approach better than the append

Comment (sagikazarmark) [reply internal/providers/pke/pkeworkflow/update_cluster.go]: Append dynamically resizes the underlying array, while this approach does not require that.

Comment (siliconbrain) [reply internal/providers/pke/pkeworkflow/update_cluster.go]: Not necessarily. `append` only resizes the slice when its capacity would be exceeded. If the initial capacity is chosen well, no resizing will happen. Also, append will fill the slice without leaving "gaps", while explicit indexed assignment might leave gaps when non-assigning branches are taken (see the nil ptr problem above).

Comment (sagikazarmark) [reply internal/providers/pke/pkeworkflow/update_cluster.go]: In this case not leaving gaps is not an option, because the index is used to access elements in the original slice.
