### PR TITLE
vault-is: fix service account token visibility race-condition

### LINKED ISSUE #2726: [integrated-services/vault] fix ServiceAccount token creation race condition
**Describe the bug**

**Steps to reproduce the issue:**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by bonifaido**
Signed-off-by: Nandor Kracser <bonifaido@gmail.com>

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #2726 
| License         | Apache 2.0

### What's in this PR?

Retrying to query the service account token for vault for doing token reviews until the actual token material becomes visible in the Data field.

### Additional context

**squash please**

### Checklist

- [x] Implementation tested (with at least one cloud provider)
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)

### CODE REVIEW

File: internal/integratedservices/services/vault/operator.go [hunk 1]
```diff
@@ -184,9 +187,30 @@ func (op IntegratedServicesOperator) configureClusterTokenReviewer(
...
+
+		err = op.kubernetesService.EnsureObject(ctx, clusterID, &serviceAccountToken)
+		if err != nil {
+			return errors.WrapIf(err, "failed to query token reviewer ServiceAccount token")
+		}
 
-	return tokenReviewerJWT, nil
+		tokenReviewerJWT = string(serviceAccountToken.Data[corev1.ServiceAccountTokenKey])
+		if tokenReviewerJWT == "" {
+			return errors.New("tokenReviewerJWT is still empty")
```
Comment (siliconbrain) [inline internal/integratedservices/services/vault/operator.go]:
```suggestion
			return errors.New("tokenReviewerJWT is empty")
```
