### PR TITLE
Fix: add node pool to PKE on AWS

### LINKED ISSUE #2103: Adding new node pool to existing PKE on AWS cluster fails
**Describe the bug**
Adding a new node pool to existing PKE on AWS cluster fails with error message `failed to fetch bootstrap command: can't find nodepool "<new_node_pool>"`

**Steps to reproduce the issue:**
Create a PKE cluster on AWS. Once the cluster is up and running update it by adding a new node pool to it.

**Expected behavior**
The cluster to be expanded with the newly added node pool.

### PR DESCRIPTION
**Pull request by stoader**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #2103
| License         | Apache 2.0

### Checklist

- [x] Implementation tested (with at least one cloud provider)
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [x] Logging code meets the guideline (TODO)

### CODE REVIEW

File: cluster/ec2_pke.go [hunk 1]
```diff
@@ -432,93 +455,99 @@ func (c *EC2ClusterPKE) UpdatePKECluster(ctx context.Context, request *pkgCluste
...
 
-	err = c.SetCurrentWorkflowID(exec.GetID())
-	if err != nil {
-		return err
+	var nodePoolsToAdd []pkeworkflow.NodePool
+	var nodePoolsToUpdate []pkeworkflow.NodePool
+	var nodePoolsToDelete []pkeworkflow.NodePool
+
+	for _, np := range clusterNodePools {
+		if np.Master || np.Name == "master" {
```
Comment (Ecsy) [inline cluster/ec2_pke.go]: Are there any known usage where `np.Master` _is_ true and `np.Name` _is not_ master?
If not, every initialisation of `PKENodePool` should set `np.Master = true` if `np.Name == "master"`. Handling `if np.Master || np.Name == "master" {` like everywhere in code is error prone.

File: cluster/ec2_pke.go [hunk 2]
```diff
@@ -432,93 +455,99 @@ func (c *EC2ClusterPKE) UpdatePKECluster(ctx context.Context, request *pkgCluste
...
+			continue
+		}
+
+		if reqNodePool, ok := reqNodePoolsMap[np.Name]; ok {
+			reqNodePool.Master = np.Master
```
Comment (Ecsy) [inline cluster/ec2_pke.go]: Is there any other possible value of `np.Master` other than false? Should set it explicitly false.
